### ISSUE TITLE
[BUG] roPresence API Error

### ISSUE THREAD

**Issue by QkeleQ10** [JiveOff/roPresence#32]
When I launched the .exe file (or when I installed the master and opened the Windows_Presence.bat file), this popped up. 
![image](https://user-images.githubusercontent.com/55982900/73203726-e7716400-413d-11ea-99c4-314a5b587816.png)
When I ran the .vbs script, this popped up. 
![image](https://user-images.githubusercontent.com/55982900/73203753-f6f0ad00-413d-11ea-8309-ffd94e1afc5a.png)

I expected to see this:
![image](https://user-images.githubusercontent.com/55982900/73203867-2e5f5980-413e-11ea-94fc-d0d3ae363aaa.png)

 - OS: Windows
 - Version: Latest

**Comment by Jaguar-515** [comment]
Can reproduce this on Windows 10 1909 Build 18363.592.

**Comment by QkeleQ10** [comment]
My Windows 10 version is 2004, my build is 19037.1 (Insider Fast ring)

**Comment by febrance** [comment]
happens all the time for like 2-3 weeks now

**Comment by Skivad-ananas** [comment]
I'm also experiencing this error every time I open it.

**Comment by LingleDev** [comment]
I'm also getting this when I try to use RoPresence.

**Comment by ArtelTroyard** [comment]
I am experiencing the same error as the above whenever I open it.

**Comment by QkeleQ10** [comment]
I'm just going to tag @JiveOff on this, as this seems like an issue that's present for a lot of people.

**Comment by MacaylaMarvelous81** [comment]
Server is refusing connection

**Comment by purn8r** [comment]
I am experiencing this error as well.
Log in text form (removing my discord id) in case
[roPresence_log.txt](https://github.com/JiveOff/roPresence/files/4353094/roPresence_log.txt)
 I didn't upload the file properly:
* Non-terminal slave process launched.

 **********************************************************************************************
 *** roPresence v2.0.0 Launched: Thu Mar 19 2020 00:31:52 GMT-0600 (Mountain Daylight Time) ***
 **********************************************************************************************

RPC: Attempting to login through IPC.
roPresence Express kill server online.
RPC: Logged in as purn8r.
Socket Client: Starting.
Socket Client: Connected to socket, authenticating.
Socket Client: Authenticated to socket, ready.
roPresence: Stopping. Exiting cmd in 10 seconds.
roPresence API Error: roPresence ran into an error and had to stop. This error is mainly due to a remote API problem.
Please restart the presence.
FetchError: request to http://vps1.jiveoff.fr:3000/presences/136678156 failed, reason: socket hang up
 * Non-terminal slave process launched.

 **********************************************************************************************
 *** roPresence v2.0.0 Launched: Thu Mar 19 2020 00:35:54 GMT-0600 (Mountain Daylight Time) ***
 **********************************************************************************************

RPC: Attempting to login through IPC.
roPresence Express kill server online.
RPC: Logged in as purn8r.
Socket Client: Starting.
Socket Client: Connected to socket, authenticating.
Socket Client: Authenticated to socket, ready.
FetchError: request to http://vps1.jiveoff.fr:3000/presences/136678156 failed, reason: socket hang up
roPresence API Error: roPresence ran into an error and had to stop. This error is mainly due to a remote API problem.
Please restart the presence.
roPresence: Stopping. Exiting cmd in 10 seconds.

 **********************************************************************************************
 *** roPresence v2.0.0 Launched: Thu Mar 19 2020 01:01:39 GMT-0600 (Mountain Daylight Time) ***
 **********************************************************************************************

 * Non-terminal slave process launched.
RPC: Attempting to login through IPC.
roPresence Express kill server online.
RPC: Logged in as purn8r.
Socket Client: Starting.
Socket Client: Connected to socket, authenticating.
Socket Client: Authenticated to socket, ready.
roPresence API Error: roPresence ran into an error and had to stop. This error is mainly due to a remote API problem.
Please restart the presence.
roPresence: Stopping. Exiting cmd in 10 seconds.

**Comment by Jaguar-515** [comment]
Well, looks like Jive doesn't care about roPresence at all.

**Comment by JiveOff** [comment]
Hello there,
The API is working like a charm for me.

Are you still experiencing this issue?

**Comment by MacaylaMarvelous81** [comment]
Nope, the API is working now. Thank you for making this wonderful application.
